[package]
name = "webcam_viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.23.0"
egui = "0.23.0"
ndarray = "0.15.6"
rayon = "1.8.0"
v4l = "0.14.0"
